name: vhu_helps_map
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.6.0
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  google_sign_in: ^6.2.2
  flutter_feather_icons: ^2.0.0
  material_design_icons_flutter: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env # Khai báo tệp .env để Flutter có thể đọc được
    - assets/images/
